---
- name: ensure roles folder exists
  file:
    path: "{{ netlab_odl_roles }}"
    state: directory

- name: clone roles to local roles folder
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.branch }}"
  with_items:
    - repo: "git@github.com:ansible-odl/l3vpn"
      dest: "{{ netlab_odl_roles }}/ansible-network.l3vpn"
      branch: devel
    - repo: "git@github.com:ansible-odl/network-engine"
      dest: "{{ netlab_odl_roles }}/ansible-network.network-engine"
      branch: l3vpn
    - repo: "git@github.com:ansible-odl/cisco_ios"
      dest: "{{ netlab_odl_roles }}/ansible-network.cisco_ios"
      branch: l3vpn
    - repo: "git@github.com:ansible-odl/arista_eos"
      dest: "{{ netlab_odl_roles }}/ansible-network.arista_eos"
      branch: devel

